### ISSUE TITLE
Feature/status request: NRPcalc for CDS's

### ISSUE THREAD

**Issue by eyesmo** [ayaanhossain/nrpcalc#2]
Hi! Howard mentioned you're working on a nonrepetitive parts calculator for protein coding sequences. How's that going? Would love to use it for some projects. I've found it difficult to use the regular nrpcalc for this task--most queries end up with no solved sequences, and no indication what regions of the sequence are causing problems.

**Comment by hsalis** [comment]
Hello Isaac,

   The prototype is done & tested. I can prepare the web interface
(sometime this week) & throw it up on our test server for your usage.

   Regarding the solution space: If Lmax is too small and/or if the CDS is
very polymeric, then the # of non-repetitive CDSs will indeed be small.
Though I routinely received 10+ non-repetitive CDSs with 300 randomly
generated AA sequences with an Lmax of 20. But an Lmax of 15 reduced the
solution set to 2-3 CDSs. So your best strategy is to start off with a high
Lmax. On the website, it will automatically calculate the solution set with
lower and lower Lmax until some threshold is reached.

Thanks,
   Howard


~~
Howard Salis
Associate Professor
Biological Engineering and Chemical Engineering
Penn State University

Email: salis@psu.edu
Phone: 814-865-1931
Lab web site: http://salislab.net
Design your DNA: http://salislab.net/software

**Comment by hsalis** [comment]
And it's done. I'll DM you our test server URL. Let me know how it goes.
